### ISSUE TITLE
Invalid or unexpected token 

### ISSUE THREAD

**Issue by AyuB911** [LevitatingBusinessMan/twitch-drop-farm#2]
SyntaxError: Invalid or unexpected token
[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m
PS C:\Users\Usuario\Desktop\twitch-drop-farm-cookie>

you can help me?

**Comment by LevitatingBusinessMan** [comment]
This is might a problem with your version of NodeJS. What version are you using?

**Comment by AyuB911** [comment]
I am using version 12.17, but that does not happen for the problem, I think the problem is the "token", I access the "twitchtokengenerator.com" website and the account's token or token, I don't know if that's the case;
